apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nodelabel
  name: nodelabel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodelabel
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodelabel
    spec:
      containers:
      - image: debian
        name: debian
        resources: {}
status: {}