apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: deployment
  name: deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: deployment
    spec:
      nodeSelector:
        color: red
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}