apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: prod-user
spec:
  groups:
  - system:authenticated
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ2FqQ0NBVklDQVFBd0pURVNNQkFHQTFVRUF3d0pjSEp2WkMxMWMyVnlNUTh3RFFZRFZRUUtEQVprWlhadgpjSE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRRERTQzRTQy8wMzZzYTlOeE5jCjVmUGhqQW4vTnZXR0RBbGkzbVhLYVN4UytzVWV2cFA2Ulc4Nyt3R2hkZEJJZzlicWJIZUNoZmhUcmVlS1F1UHoKeTBJczJya0t6dkNMZXVSUWZZSCtMam1OaWRLQVNCdUxnYURkaHRycWhvZ0dqTTFQSGxXelNmajlzQ3BJR0JNSgplRWtzTlJzcFkwa08wVCtmMElBaTcwcnFoV3dDNmNFNS9sU0lnN2J0TTJtaXVLWUl6MkhtQUt4d0VJb1F5U3RBCkdWdGR5cnVrU2ozdGdXZDdFckNPRkFtVThHRm42eWJjQnFuVkZYL1RqZm83K25BVVFNSlZFWHk4QWpKVmNJNHEKNHRFdlI5OVJ0TGR2VWZYamlwdFFsZlFFVCt3YVVxUFZHOWdrMktmQlZZak1jY1JhOW9hNE5BdVhKZE5ha2J5agplbVFoQWdNQkFBR2dBREFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBb3krWE8zSkZKQ0d2MHVtU3Mydy9JQ1l1CnhLTWFCUmZralFDdnRRQWlwQ055Wng1c3BqZ0M0aEtGWHVENGk0aEFqV0w5d281VWVoS0dKZmx1MHViN1piTnYKaldyTEY5R0tmTUNUeXd6YitVaE5uQm5IWnY2U0NTUkJ3OXhHS2s4YTErdTVxTXUwYWVpUkgxVHNHaFI0VHptZApnenJKUEVQOU9sK1NSUWJDU0VlMk5ILzc2eDVhSW95cUIvM3JPUjBNcmhDblk3cGM1N09WVFdoNU0xTXpsQlpCCkpaRDE4d2RwL241aGhRU2RKY0lvMkVSZXliZ21GTnpyVHNNK1N0NFpYSzYrWE1DVDFFcXVSbmlFQzVWY3hNbXoKcDhQUHRkTWg0aENmeWdUVEJMNDB4TGpHQ0FDWDFibHJJR2ZBdWc1ckR2MWNDck9IY25XUkltbTZuK2dMYUE9PQotLS0tLUVORCBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0K
  signerName: kubernetes.io/kube-apiserver-client
  usages:
  - client auth
  - server auth
  - digital signature
  - key encipherment

