apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: countdown
  labels:
    env: prod
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          name: countdown
        spec:
          containers:
          - image: debian
            name: debian
            command:
            - bin/bash
            - -c
            - for i in 9 8 7 6 5 4 3 2 1 ; do echo $i ; done
          restartPolicy: Never