apiVersion: v1
kind: ConfigMap
metadata: 
  name: configmap2
data:
  index.html: |
    <H1>Hello world!</H1>
---
apiVersion: v1
kind: Pod
metadata:
  name: nginxconfigmap
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - mountPath: /usr/share/nginx/html/
      name: configmap
      readOnly: true
  volumes:
    - name: configmap
      configMap:
        name: configmap2
