apiVersion: v1
kind: ConfigMap
metadata:
  name: newconfigmap
data:
  db: mysql
  driver: odbc
---
apiVersion: v1
kind: Pod
metadata:
  name: pod1
  labels:
    environment: preprod
spec:
  containers:
  - image: nginx
    name: nginxserver
    env:
    - name: KEY1
      valueFrom:
        configMapKeyRef:
          name: newconfigmap
          key: db
    - name: KEY2
      valueFrom:
        configMapKeyRef:
          name: newconfigmap
          key: driver