apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: hostpath
  name: hostpath
spec:
  nodeSelector:
    env: dev
  containers:
  - image: ubuntu
    name: hostpath
    command: ['/bin/bash','-c','echo hello world; sleep 9000']
    volumeMounts:
    - mountPath: /ubuntuvol
      name: hostpathvol
  - image: centos
    name: centos
    command: ['/bin/bash','-c','echo hello world; sleep 9000']
    volumeMounts:
    - mountPath: /centosvol
      name: hostpathvol
  - image: alpine
    name: alpine
    command: ['/bin/sh','-c','echo hello world; sleep 9000']
    volumeMounts:
    - mountPath: /alpinevol
      name: hostpathvol
  volumes:
  - name: hostpathvol
    hostPath:
      path: /tmp/test
  dnsPolicy: ClusterFirst
  restartPolicy: Always
