apiVersion: v1
kind: Namespace
metadata:
  name: hwquota

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: resourcequota
  namespace: hwquota
spec:
  hard:
    requests.cpu: "1"
    requests.memory: "1Gi"
    limits.cpu: "2"
    limits.memory: "2Gi"