apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: resourcequota

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: resourcequota
  namespace: resourcequota
spec:
  hard:
    pods: "10"
    replicationcontrollers: "5"
    services: "4"
    count/deployment.apps: "3"
    count/replicaset.apps: "4"