apiVersion: v1
kind: Pod
metadata:
  name: environmentvariable
  labels:
    env: prod
    owner: infra
spec:
  containers:
  - name: nginx
    image: nginx
    env:
    - name: port
      value: "8080"
    - name: user
      value: henry