apiVersion: v1
kind: Pod
metadata:
  name: init-container

spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: initvol
      mountPath: /usr/share/nginx/html
    ports:
    - containerPort: 80
  volumes:
  - name: initvol
    emptyDir: {}
  initContainers:
  - name: alpine
    image: alpine
    volumeMounts:
    - name: initvol
      mountPath: /init-container
    command: 
    - sh
    - "-c"
    - |
      mkdir -p /init-container && \
      echo "welcome to init container" > "/init-container/index.html"
      sleep 60

