apiVersion: v1
kind: Pod
metadata:
  name: sidecar

spec:
  volumes:
  - name: html
    emptyDir: {}
  containers:
  - name: httpd
    image: httpd
    volumeMounts:
    - name: html
      mountPath: /usr/local/apache2/htdocs
  - name: debian
    image: debian
    volumeMounts:
    - name: html
      mountPath: /usr/local/apache2/htdocs
    command: ["/bin/sh", "-c"]
    args:
     - while true; do
       echo "current date is:" > /usr/local/apache2/htdocs/index.html;
       date >> /usr/local/apache2/htdocs/index.html;
       sleep 100;
       done